### ISSUE TITLE
More colors for sender in style?

### ISSUE THREAD

**Issue by davewaxman** [FroZnShiva/base16-builder-textual#3]
Greetings,

First and foremost I absolutely love your style collection. I have been using Tomorrow Night Eighties (which I assume is older than the ones in this collection) for a while now and just found this collection.

I however would love to see more variation in colors available for the nicknames who send messages in channel. I know Textual has a limit of 31; but I also know this can be avoided using some magical code I don't understand. It is done in the nox and equinox styles. Is this something that can be added to your collection?

**Comment by FroZnShiva** [comment]
This will probably be obsolete with the new Textual color system:

> One of the most popular complaints about Textual is that the color assigned to each user in a channel can often times be the same for multiple users. 
> 
> When finished, Textual 5.2.5 will introduce an optional way by which colors are assigned to each user. The new option will generate a [hue, saturation level, and lightness level (HSL)](https://en.wikipedia.org/wiki/HSL_and_HSV) for each user. By dynamically generating these values, instead of being limited to 31 specific colors, the new system will hopefully make repeated colors much less common.

**Comment by davewaxman** [comment]
Indeed. Thank you.
