### ISSUE TITLE
Tomorrow Night: unreadable links in topic

### ISSUE THREAD

**Issue by Jay2k1** [FroZnShiva/base16-builder-textual#6]
The topic bar on the **tomorrow night (eighties)** theme is so translucent that it's really hard to read links in a topic if there's channel text underneath: 
![image](https://cloud.githubusercontent.com/assets/2070503/18391112/29f979ac-76ad-11e6-8d70-9a8c7d59f56d.png) 
Even if there's nothing underneath (take the topic beginning with znc.in in my screenshot), it's not very readable... blue on green is probably not the best combination for readability.

**Comment by FroZnShiva** [comment]
This actually refers to [FroZnShiva/Textual-Style-Tomorrow_Night_Eighties](/FroZnShiva/Textual-Style-Tomorrow_Night_Eighties). But in the builder script the color selection for RGB values is not taking the inversion for dark schemes into account – which results in topic bars even less readable.
